#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
import os
import sys
import time
import string
from std_msgs.msg import String
from qt_robot_interface.srv import *
from qt_gesture_controller.srv import *
from std_msgs.msg import Float64MultiArray
from sensor_msgs.msg import JointState


def choose_behaviors(number, right_pub, left_pub, head_pub, emotionShow_pub, gesturePlay_pub, speechSay_pub, audioPlay_pub):

    #talking:1~6
    if(number == 1):
    #show_both_hands:6.5s
        emotionShow_pub.publish("QT/talking")
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        left_arm.data = [10, -60, -15]
        left_pub.publish(left_arm)
        time.sleep(2)
        right_arm.data = [-10, -60, -15]
        right_pub.publish(right_arm)
        time.sleep(2)
        left_arm.data = [90, -60, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-90, -60, -30]
        right_pub.publish(right_arm)
        time.sleep(2.5)    
    elif(number == 2):
    #hold:5s
        gesturePlay_pub.publish("QT/show_QT")
        emotionShow_pub.publish("QT/talking")
        time.sleep(5)
    elif(number == 3):
    #challenge:5s
        gesturePlay_pub.publish("QT/challenge")
        emotionShow_pub.publish("QT/talking")
        time.sleep(5)
    elif(number == 4):
    #show left and right:10s
        gesturePlay_pub.publish("QT/show_left")
        emotionShow_pub.publish("QT/talking")
        time.sleep(5)
        gesturePlay_pub.publish("QT/show_right")
        emotionShow_pub.publish("QT/talking")
        time.sleep(5)
    elif(number == 5):
    #pointing:6s
        emotionShow_pub.publish("QT/talking")
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        left_arm.data = [110, -60, -10]
        right_arm.data = [0, -90, -10]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(3.5)
        left_arm.data = [90, -60, -30]
        right_arm.data = [-90, -60, -30]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(2.5)   
    elif(number == 6):
    #point each:8.5s
        emotionShow_pub.publish("QT/talking")
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        left_arm.data = [0, -90, -10]
        left_pub.publish(left_arm)
        time.sleep(2)
        left_arm.data = [90, -60, -30]
        left_pub.publish(left_arm)
        time.sleep(2)
        emotionShow_pub.publish("QT/talking")
        right_arm.data = [0, -90, -10]
        right_pub.publish(right_arm)
        time.sleep(2)
        right_arm.data = [-90, -60, -30]
        right_pub.publish(right_arm)
        time.sleep(2.5) 


    #listening:7~8
    elif(number == 7):
    #nod:4s
        head = Float64MultiArray()
        emotionShow_pub.publish("QT/showing_smile")
        head.data = [0,-10]
        head_pub.publish(head)
        time.sleep(1)
        head.data = [0,10]
        head_pub.publish(head)
        time.sleep(1)
        head.data = [0,0]
        head_pub.publish(head)
        time.sleep(2)
    elif(number == 8):
    #arm back smile:7s
        emotionShow_pub.publish("QT/calming_down")
        time.sleep(1)
        gesturePlay_pub.publish("QT/bored")
        time.sleep(6)    


    #guessing:9~11
    elif(number == 9):
    #confused:8s
        right_arm = Float64MultiArray()
        right_arm.data = [40, -60, -90]
        right_pub.publish(right_arm)
        time.sleep(2)
        emotionShow_pub.publish("QT/confused")
        time.sleep(2)
        right_arm.data = [-90, -60, -30]
        right_pub.publish(right_arm)
        time.sleep(4)
    elif(number == 10):
    #touch head:11s
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        left_arm.data = [-80, -40,-80]
        right_arm.data = [80, -40,-80]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(3)
        emotionShow_pub.publish("QT/confused")
        left_arm.data = [-100, -40,-80]
        right_arm.data = [100, -40,-80]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-80, -40,-80]
        right_arm.data = [80, -40,-80]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-100, -40,-80]
        right_arm.data = [100, -40,-80]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-80, -40,-80]
        right_arm.data = [80, -40,-80]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [90, -60,-30]
        right_arm.data = [-90, -60,-30]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(4)
    elif(number == 11):
    #thinking:10s
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        left_arm.data = [-90, -50, -30]
        right_arm.data = [-90, -45, -90]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(3.5)
        emotionShow_pub.publish("QT/confused")
        left_arm.data = [-90, -70, -40]
        right_arm.data = [-90, -45, -90]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-90, -50, -30]
        right_arm.data = [-90, -45, -90]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-90, -70, -40]
        right_arm.data = [-90, -45, -90]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [-90, -50, -30]
        right_arm.data = [-90, -45, -90]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [90, -60, -30]
        right_arm.data = [-90, -60, -30]
        left_pub.publish(left_arm)
        right_pub.publish(right_arm)
        time.sleep(2.5)  


    #feedback and encouragement:12~15
    elif(number == 12):
    #surprise:5.5s
        gesturePlay_pub.publish("QT/surprise")
        emotionShow_pub.publish("QT/surprise")
        time.sleep(5.5)
    elif(number == 13):
    #happy:5s
        gesturePlay_pub.publish("QT/happy")
        emotionShow_pub.publish("QT/happy")
        time.sleep(5)
    elif(number == 14):
    #hug:6s
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        emotionShow_pub.publish("QT/happy")
        left_arm.data = [-20, -10, -15]
        left_pub.publish(left_arm)
        right_arm.data = [20, -10, -15]
        right_pub.publish(right_arm)
        time.sleep(3)
        left_arm.data = [90, -60, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-90, -60, -30]
        right_pub.publish(right_arm)
        time.sleep(3)
    elif(number == 15):
    #hand clap:8.8s
        left_arm = Float64MultiArray()
        right_arm = Float64MultiArray()
        emotionShow_pub.publish("QT/happy")
        left_arm.data = [10, -90, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-10, -90, -30]
        right_pub.publish(right_arm)
        time.sleep(1.8)
        left_arm.data = [10, -90, -90]
        left_pub.publish(left_arm)
        right_arm.data = [-10, -90, -90]
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [10, -90, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-10, -90, -30]
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [10, -90, -90]
        left_pub.publish(left_arm)
        right_arm.data = [-10, -90, -90]
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [10, -90, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-10, -90, -30]
        right_pub.publish(right_arm)
        time.sleep(1)
        left_arm.data = [90, -60, -30]
        left_pub.publish(left_arm)
        right_arm.data = [-90, -60, -30]
        right_pub.publish(right_arm)
        time.sleep(3)


    #personility:16~18
    elif(number == 16):
    #hi/bye:7s
        gesturePlay_pub.publish("QT/hi")
        emotionShow_pub.publish("QT/happy")
        time.sleep(7)
    elif(number == 17):
    #fly kiss:7.5s
        gesturePlay_pub.publish("QT/kiss")
        time.sleep(1)
        emotionShow_pub.publish("QT/kiss")
        time.sleep(6.5)
    elif(number == 18):
    #yawn:6.8s
        gesturePlay_pub.publish("QT/yawn")
        time.sleep(0.8)
        emotionShow_pub.publish("QT/yawn") 
        time.sleep(6)
    else:
        print("Please use a correct number!")
